name: PR Automation

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - converted_to_draft

permissions:
  pull-requests: write
  issues: write

jobs:
  pr-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Add WIP Label on Open
        if: github.event.action == 'opened'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: WIP
        run: gh issue edit "$NUMBER" --add-label "$LABELS"

      - name: Add WIP Label on Draft
        if: github.event.action == 'converted_to_draft'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: WIP
        run: gh issue edit "$NUMBER" --add-label "$LABELS"

      - name: Remove WIP and Add Ready Label
        if: github.event.action == 'ready_for_review'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: -WIP,ready-for-review
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
